#!/usr/bin/python3

import os.path as osp
import os
from typing import List
import subprocess

# Create new .md file

content_types:List[str] =  os.listdir("./content")
for i, c in enumerate(content_types):
    print(i, ":", c)
content_type = content_types[int(input("hugo page type (int):"))] 
filename = input("filename (no .md extension):")
res = subprocess.run(["hugo", "new", content_type + "/" + filename + ".md"], capture_output=True, text=True)

print(filename,end="")

