#!/usr/bin/python3

import os.path as osp
import os
import pathlib
import json
from typing import Dict
import sys

# Create new .md file

if not sys.stdin.isatty():
    filename = sys.stdin.read().strip()
    sys.stdin = open('/dev/tty')
else:
    filename = input("filename (no .md ext):")


data: Dict
DATAI=["Usage", "History", "Package"]
DATAF="./data/commands.json"

p = pathlib.Path(__file__)
os.chdir(p.parent.absolute())

if osp.exists(DATAF):
    with open(DATAF,"r") as f:
        data = json.load(f)
else:
    print("Missing data file")
    exit(1)

data[filename]= {key: input(key + ":") for key in DATAI}

with open(DATAF, "w") as f:
    json.dump(data, indent=3,fp=f)

print(filename, end="")
exit(0)

