
baseURL: "https://www.linux-toolkit.com/"
languageCode: "en-us"
title: "GNU/Linux Toolkit"
theme: "hyde"
sectionPagesMenu: "main"
publishDir: ".public"
resourceDir: ".resources"
themesDir : ".themes"

#module:
  #mounts:
    #- source: /home/andy/.nb/tools
      #target: content/tools

Params:
  description: "Consise command line refreshers"

markup:
  goldmark:
    extensions:
      table: true
      definitionList: true
    renderer:
      unsafe: true



#Menus:
  #main:
